services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend

  www:
    build:
      context: .
      dockerfile: docker/www.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend

  runner:
    build:
      context: .
      dockerfile: apps/runner/Dockerfile
    env_file:
      - apps/runner/.env
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
